[package]
name = "reboot-ubiquiti-nano-beam-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
headless_chrome = "1.0.5"
